Switch to MacOS Tahoe for iOS workflows
Upgraded to MacOS 26 because workflows have started suffering from
what appears to be some form of homebrew corruption.

While talking with Emils about this, Tahoe runners seemed to work
fine, which is why we're switching that first.

Further investigation may be needed.

## References
Failing job:
https://github.com/mullvad/mullvadvpn-app/actions/runs/24882042581/job/72852634858

Logs for reference:

```
# Installing xcbeautify, which does not actually install due to
already being present
Run brew update
  brew update
  brew install xcbeautify
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SOURCE_PACKAGES_PATH: .spm
==> Updating Homebrew...
To restore the stashed changes to /opt/homebrew/Library/Taps/homebrew
/homebrew-core, run:
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash 
  pop
==> Homebrew's analytics have entirely moved to our InfluxDB instance
  in the EU.
  We gather less data than before and have destroyed all Google
  Analytics data: https://docs.brew.sh/Analytics
  Please reconsider re-enabling analytics to help our volunteer
  maintainers with: brew analytics on
==> Homebrew is run entirely by unpaid volunteers. Please consider
  donating:
  https://github.com/Homebrew/brew#donations

Updated 4 taps (hashicorp/tap, aws/tap, homebrew/core and homebrew/
cask).
==> New Formulae
floresta: Lightweight and embeddable Bitcoin client, built for
sovereignty forgecode: AI-enhanced terminal development environment
lazymake: Modern TUI for Makefiles
try: Quickly manage and navigate project directories for experiments
vite-plus: Unified toolchain and entry point for web development
==> New Casks
hop: View and edit HWP documents
paranoia-file-text-encryption: File and text encryptor with
steganography and post-quantum key exchange

==> Outdated Formulae
certifi
cmake
gh
kotlin
node@22
pydantic
simdutf

You have 7 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
Warning: xcbeautify 3.2.1 is already installed and up-to-date.
To reinstall 3.2.1, run:
  brew reinstall xcbeautify

# Install Protobuf, which fails
Run brew update
  brew update
  brew install protobuf
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SOURCE_PACKAGES_PATH: .spm
lockf: 200: already locked
Error: Another `brew update` process is already running.
Please wait for it to finish or terminate it to continue.
```